### ISSUE TITLE
Scanlines Need to be Toggleable

### ISSUE THREAD

**Issue by akgunter** [akgunter/crt-royale-reshade#2]
Sometimes the scanline autodetection logic doesn't get along with ReShade's architecture. There needs to be a setting that lets users force them on or off regardless of the resolution.

I also need to investigate their quality. It looks like they looked awful earlier because I needed to enable vsync in snes9x, so maybe I don't need to rewrite the scanline code.

Reported in Issue #1

**Comment by akgunter** [comment]
It turns out that there's more to the scanlines than just making them toggleable. RetroArch does some kind of sorcery that causes the scanlines to be 2 pixels high despite all the math treating them as if they're only 1 pixel high. And it's not just a simple matter of aspect ratio weirdness. With the Super Metroid title screen as the test case, you can compare the alignment of the phosphor mask with the game's artwork and see that it only matches RetroArch's alignment if you pass in a 4:3 source. This tells me that the RetroArch version of crt-royale is also receiving a 4:3 source, so the 2-pixel height isn't a side effect of the emulator rescaling the SNES output from 8:7 to 4:3.

My workaround is to just make the scanline thickness configurable by the user, with a default of 2 instead of 1. I just pushed a branch that implements a first-pass of that and gets most of the perceived effect fixed.

The biggest difference right now is that something is causing too much vertical-bloom and not enough horizontal-bloom, most likely some residual "thickness 1" logic strewn about the pipeline. It makes the image more color-neutral than the RetroArch version and more blurry.

I'm also finding the effect to be extremely sensitive to vsync hiccups, especially with Sample Mode 1. I'd like it to be smoother if possible.

**Comment by JohnEdwa** [comment]
Is the "Enable Interlacing" a required setting for the scanlines to work? Because unless your game FPS and monitor refresh rate are *perfectly* aligned, the interlacing goes out of sync and causes terrible flickering.

**Comment by akgunter** [comment]
Yeah, unfortunately all of the logic for the scanlines and the interlacing are woven extremely tightly together. On top of that, the blur effect resulting from the interlacing is an integral part of the perceived image; and disabling it messes it up really badly. I have a rough idea for how to address all of that, but it would be a completely new scanline pipeline if I can figure out how to code it.

**Comment by akgunter** [comment]
Closing because this is working as it does in the original shader now.

**Comment by billbeans** [comment]
Can somebody tell me how to enable scanlines by manually editing the files? I'm using this shader with vkbasalt on Linux, so I don't have access to the Reshade UI. I'm using this fork as well, which seems to have been made after these changes were applied: https://github.com/andersstorhaug/crt-royale-reshade/tree/vkbasalt

Edit: I feel dumb, there is clearly a `user-settings.fxh` file inside the `lib` folder. I will try editing this, but I haven't changed anything yet

Edit2: `bind-shader-params.fxh` in the `lib` folder has a section titled `uniform uint scanline_thickness <` where you can adjust the scanline thickness, but much like the user states in [this issue](https://github.com/akgunter/crt-royale-reshade/issues/8) it's just not looking right to me. The screenshots [here on the Emu wiki](https://emulation.gametechwiki.com/index.php/CRT-Royale) just look different, but maybe I still need to get used to it. I know that they must be using a thicker scanline setting than the default. I'm using 6 for now, I think it looks a bit better, and I do have a 4K monitor

**Comment by billbeans** [comment]
I took a direct comparison of one of the screenshots on that page: MediEvil 1 for the PS1, with mednafen as the emulator:

EmuWiki:

<img width="2880" height="2160" alt="Image" src="https://github.com/user-attachments/assets/13322ae4-5325-4d49-8c54-83f1372bc64e" />

crt-royale-reshade:

<img width="2880" height="2160" alt="Image" src="https://github.com/user-attachments/assets/f750b2fc-25d3-42cd-8ed7-a40f5d7d6639" />

The only change I made was bumping up the scanline thickness to 6
