### ISSUE TITLE
Getting error error X3535: Bitwise operations not supported on target ps_3_0 Half-Life 2

### ISSUE THREAD

**Issue by Hillionliat** [akgunter/crt-royale-reshade#27]
Hello, I've wanted to try out the new 2.0 version if CRT-royale, but I've got a problem I've wanted to run HL2 with reshade through dx9 because it's a dx9 game, but I get this error "X3535: Bitwise operations not supported on target ps_3_0" during compiling of shaders
I hope it's not an issue with DX9 because it is said that you do have DX9 support for this shader and most old games i use crt for run on DX9

**Comment by akgunter** [comment]
No, it's a mistake on my end. I must have added a bitwise op somewhere without thinking about it. Lemme see if I can find it, and I'll release an update.

**Comment by akgunter** [comment]
Alright, that's fixed, tested, and released now. It should be behaving itself in DX9 again.
