### ISSUE TITLE
Are the scanlines supposed to be vertical?

### ISSUE THREAD

**Issue by maverick-hunter** [akgunter/crt-royale-reshade#8]
I tried all the settings in a few games and no matter what I do, the scanlines always look vertical to me. Am I doing something wrong?

**Comment by JohnEdwa** [comment]
Scanlines are only enabled with interlacing on and are very clear vertical black bars between the pixels, the thickness of which you can change using the config option. You are most likely confusing them with the mask.
If you attach a screenshot, it should be fairly easy to tell if this is the case.

**Comment by maverick-hunter** [comment]
I see. I zoomed in a screenshot and I think you're right, but the effect is so subtle I couldn't really see it in the games I tested (it feels a mix between vertical and squared). I guess I must be too used to the lower res games on retroarch in which the default presets make the scanlines very noticeable and I was indeed trying with interlacing off at first. Thanks for the help :)

**Comment by PimpUigi** [comment]
I do believe what he means is that, the direction of the Mask/Grille is different from on RetroArch.
The mask is vertically aligned in ReShade while Horizontally aligned in RetroArch.

RetroArch:
![image](https://user-images.githubusercontent.com/7344271/140610088-4045a81e-4076-4c4f-b0da-0d53a454776d.png)
![image](https://user-images.githubusercontent.com/7344271/140610092-c39c3c61-2f19-42f1-930e-859af30aa33d.png)

ReShade:
![image](https://user-images.githubusercontent.com/7344271/140610194-3f484da6-e982-4123-818c-a60ea01991d8.png)

Now I'm not even going to lie, I like the vertical grille more; and TV's/monitors somethimes had a vertical grille instead of a horizontal one...but this would definitely be a desired option by people who expect to have horizontal bares between pixels instead of vertical ones; regardless of interlacing (which is disabled in all three of my pictures).

**Comment by MilkManEX** [comment]
You're seeing the grille interact with the scalines in those Lion King shots. The grille is still vertically oriented in the RetroArch version of reshade, but it looks like you have the triads set to 1 in shader parameters.

Some shots with a preset edited to nearly obliterate scanlines:

Triads at 1:
![image](https://user-images.githubusercontent.com/16171167/140614107-6ef8ebb1-57f7-4c20-b908-51a831a2caf6.png)

Triads at 6:
![image](https://user-images.githubusercontent.com/16171167/140614091-f2278457-84bc-45a1-b5da-b51f1270bd98.png)

The preset I'm using gives very bold scanlines so I generally don't see the mask as clearly as you will in the ReShade implementation, but you really shouldn't be seeing the mask that clearly in the first place. I've been yelling at whoever will listen to load up GTUv50 ahead of CRT-Royale to somewhat replicate the intended function of RetroArch's implementation:

![image](https://user-images.githubusercontent.com/16171167/140614375-222b3b9e-54ff-4f96-a2c0-e9413abcf73f.png)

**Comment by PimpUigi** [comment]
I'm actually very thankful that the ReShade implementation of this doesn't leave horizontal scanlines when I set triads to 1.
I get a completely smooth picture and that's perfect:
![image](https://user-images.githubusercontent.com/7344271/140615004-1cb89dd0-038c-4db9-9bae-1df7f5259bc3.png)
I've used another reshade filter to blur properly so the dithering on the crystals becomes transparent and this looks how my Sony XBR960 used to look, as well as a Luma Sharpen filter to help the sharpness get up a bit. (really wish I could make things *a ton* sharper but it is what it is, CRT magic made these games sharp and can't seem to recreate that yet)

Scanlines actually bug the hell out of me. lol
But I know a lot of people want them so I've just been setting up presets for what people might like to have. I was able to use CRT-Hylian to make some for the horizontal scanlines.

**Comment by MilkManEX** [comment]
Strange to me to replicate a 480p CRT image in a game made in the style of the 240p classics, but I'll not deny a man his nostalgic pleasures.

**Comment by PimpUigi** [comment]
I'm really surprised there aren't more people into replicating that look, it just feels the cleanest. If only there were some magic sharpening prayers to say to God to get it as crisp as a CRT, then we'd really be golden. After all of that blurring etc. we have to do, can't get any of the nearest neighbor nuns to play the games the way they were intended to look.
